dashboard/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'metrics.views.index', name='index'),

    url(r'^admin/', include(admin.site.urls)),
)

metrics/models.py
from django.db import models

from datetime import datetime

import requests


class Data(models.Model):
    count = models.IntegerField()
    date = models.DateTimeField(default=datetime.now)

    class Meta:
        get_latest_by = 'date'


class Metric(models.Model):
    name = models.CharField(max_length=255)
    data = models.ManyToManyField(Data, null=True, blank=True)

    class Meta:
        abstract = True


class GithubItem(Metric):
    """Example: https://api.github.com/repos/django/django/pulls?state=open"""
    url = models.URLField(max_length=1000)

    def fetch(self):
        count = 0
        page = 1
        while True:
            r = requests.get(self.url, params={
                'page': page, 'per_page': 100
            })
            c = len(r.json())
            count += c
            page += 1
            if c < 100:
                break
        return count

metrics/views.py
from metrics.models import Metric

from django.shortcuts import render


def index(request):
    metrics = []
    for MC in Metric.__subclasses__():
        metrics.extend(MC.objects.all())

    data = []
    for metric in metrics:
        latest = metric.data.latest()
        data.append({'metric': metric, 'latest': latest})
    return render(request, 'index.html', {'data': data})

metrics/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>{% block title %}Development Dashboard{% endblock %}</title>
{% load static from staticfiles %}
<link rel="stylesheet" href="{% static "dashboard.css" %}">
<script type="text/javascript" src="{% static "jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "jquery.flot.min.js" %}"></script>
<script type="text/javascript" src="{% static "dddash.js" %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
<h1>{% block pagetitle %}Development Dashboard{% endblock %}</h1>
{% block content %}{% endblock %}
	</body>
	</html>

metrics/templates/index.html
{% extends "base.html" %}

{% block extrahead %}
	{% load static from staticfiles %}
	<script type="text/javascript" src="{% static "dashboard.js" %}"></script>
{% endblock %}

{% block content %}
	{% for report in data %}
		<div>
		<h3>{{ report.metric.name }}</h3>
		<p class="value" >
		{{ report.latest.count }}
		<span class="timestamp">&nbsp;</span>
		</p>
		</div>
	{% endfor %}
	<p class="updated">
	Updated {{ data.0.latest.date|timesince }} ago.
	</p>
{% endblock %}

metrics/templates/metrics/metric_list.html
{% block content %}

{% for metric in metric_list %}
    <div id="">
        <h2>{{ metric.name }}</h2>
        open issues: {{ metric.data_set.all.0.count }}.
    </div>
{% endfor %}

{% endblock %}